version: '3'

services:
 myapp:
   restart: always
   build:
     context: .
     dockerfile: Dockerfile
   environment:
     PORT: "5000"
   ports:
     - "5000:8080"
  db:
    image: postgres:16.1
      environment:
        POSTGRES_PASSWORD: password
        POSTGRES_DB: DBName

